name: Deploy Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (optional, if using a private registry)
      # Uncomment and set secrets if necessary
      #- name: Log in to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and start services
      - name: Start Docker Compose
        run: |
          docker-compose pull
          docker-compose up --build -d

      # Step 5: Verify services are running (optional)
      - name: Verify Running Containers
        run: docker ps