name: Deploy Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        continue-on-error: false

      - name: Install Docker using Docker's official script
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
        continue-on-error: false

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
        continue-on-error: false

      - name: Run Tests
        run: |
          cd ./eureka-server
          sudo chmod +x ./mvnw
          ./mvnw test
          cd ./inventory-service
          sudo chmod +x ./mvnw
          ./mvnw test
          cd ./order-service
          sudo chmod +x ./mvnw
          ./mvnw test
          cd ./payment-service
          sudo chmod +x ./mvnw
          ./mvnw test
          cd ./product-service
          sudo chmod +x ./mvnw
          ./mvnw test
          cd ./service-discovery
          sudo chmod +x ./mvnw
          ./mvnw test
        continue-on-error: false

      # Step 4: Build and start services
      - name: Start Docker Compose
        run: |
          docker-compose pull
          docker-compose up --build -d

      # Step 5: Verify services are running (optional)
      - name: Verify Running Containers
        run: docker ps